import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the GitHub repository of this plugin:
https://github.com/polygonhunter/daily-bible-verse
*/
`;

const prod = process.argv[2] === "production";

/** Obsidian does not expose a standalone "moment" module to plugin require();
 * moment is only reachable via require("obsidian").moment. This shim redirects
 * every `require("moment")` in the bundle (ours and bundled dependencies like
 * obsidian-daily-notes-interface) to Obsidian's moment instance — without it
 * the plugin crashes on load with "Cannot find module 'moment'". */
const obsidianMomentShim = {
  name: "obsidian-moment-shim",
  setup(build) {
    build.onResolve({ filter: /^moment$/ }, () => ({
      path: "moment",
      namespace: "obsidian-moment",
    }));
    build.onLoad({ filter: /.*/, namespace: "obsidian-moment" }, () => ({
      contents: 'module.exports = require("obsidian").moment;',
      loader: "js",
    }));
  },
};

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
  ],
  plugins: [obsidianMomentShim],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  minify: prod,
  outfile: "main.js",
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
